formatter:
  type: basic
  indent: 2
  include_document_start: false
  drop_merge_tag: true
  pad_line_comments: 2
  trim_trailing_whitespace: true
  retain_line_breaks_single: true
  scan_folded_as_literal: true
