services:
  cloudflared:
    cap_drop:
      - ALL
    command:
      - tunnel
      - --no-autoupdate
      - --metrics
      - 0.0.0.0:60123
      - run
    container_name: cloudflared
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 128M
        reservations:
          cpus: 0.05
          memory: 32M
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN:?CLOUDFLARED_TUNNEL_TOKEN is required}
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 1m0s
      test:
        - NONE
      timeout: 10s
    hostname: ${TAILSCALE_HOSTNAME:?TAILSCALE_HOSTNAME is required}
    image: cloudflare/cloudflared:latest
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: 65532:65532
