services:
  intel-gpu-exporter:
    container_name: intel-gpu-exporter
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 64M
        reservations:
          cpus: 0.05
          memory: 16M
    devices:
      - permissions: rwm
        source: /dev/dri
        target: /dev/dri
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 15s
      test:
        - CMD-SHELL
        - wget -q --spider http://127.0.0.1:9090/metrics || exit 1
      timeout: 10s
    hostname: intel-gpu-exporter
    image: ghcr.io/clambin/intel-gpu-exporter:latest
    labels:
      - gatus.enable=false
    pid: host
    privileged: true
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
