services:
  authelia:
    networks:
      - default
    ports:
      - host_ip: 192.168.1.2
        published: "9091"
        target: 9091
      - host_ip: 100.100.1.2
        published: "9091"
        target: 9091
