---
connectivity:
  checker:
    interval: 30s
    target: 1.1.1.1:53
metrics: true
storage:
  path: /data/data.db
  type: sqlite
ui:
  default-sort-by: group
  favicon:
    default: https://ik.imagekit.io/technis/tr:e-colorize-co-007BFF:w-512,h-512,cm-pad_resize,bg-00000000/logo.png
    size16x16: https://ik.imagekit.io/technis/tr:e-colorize-co-007BFF:w-512,h-512,cm-pad_resize,bg-00000000/logo.png
    size32x32: https://ik.imagekit.io/technis/tr:e-colorize-co-007BFF:w-512,h-512,cm-pad_resize,bg-00000000/logo.png
  header: Mothership
  link: "https://ms.status.${DOMAIN}"
  logo: https://ik.imagekit.io/technis/tr:e-colorize-co-007BFF:w-512,h-512,cm-pad_resize,bg-00000000/logo.png
  title: Status | Mothership
web:
  port: 8080
