services:
  grafana:
    cap_drop:
      - ALL
    container_name: grafana
    depends_on:
      tempo:
        condition: service_started
        required: true
      victorialogs:
        condition: service_healthy
        required: true
      victoriametrics:
        condition: service_healthy
        required: true
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
        reservations:
          cpus: 0.1
          memory: 128M
    environment:
      - GF_METRICS_ENABLED=true
      - GF_PLUGINS_PREINSTALL_SYNC=victoriametrics-logs-datasource
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:?GRAFANA_ADMIN_PASSWORD is required}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SERVER_ROOT_URL=https://${GRAFANA_ROOT_DOMAIN:?GRAFANA_ROOT_DOMAIN is required}
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 1m0s
      test:
        [CMD-SHELL, wget -q --spider http://127.0.0.1:3000/api/health || exit 1]
      timeout: 10s
    hostname: grafana
    image: grafana/grafana:12.2.0
    labels:
      - observability.metrics.address=grafana:3000
      - traefik.enable=true
      - traefik.http.routers.grafana.middlewares=auth@file
      - traefik.http.routers.grafana.rule=Host(`${GRAFANA_ROOT_DOMAIN:?GRAFANA_ROOT_DOMAIN is required}`)
      - traefik.http.services.grafana.loadbalancer.server.port=3000
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=256m
    user: 1000:1000
    volumes:
      - ${STACK_DATA_ROOT:?STACK_DATA_ROOT is required}/grafana/dashboards:/etc/grafana/dashboards:ro
      - ${STACK_DATA_ROOT:?STACK_DATA_ROOT is required}/grafana/data:/var/lib/grafana
      - ${STACK_DATA_ROOT:?STACK_DATA_ROOT is required}/grafana/provisioning/dashboards/observability.yaml:/etc/grafana/provisioning/dashboards/observability.yaml:ro
      - ${STACK_DATA_ROOT:?STACK_DATA_ROOT is required}/grafana/provisioning/datasources/observability.yaml:/etc/grafana/provisioning/datasources/observability.yaml:ro
