services:
  kromgo:
    cap_drop:
      - ALL
    container_name: kromgo
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 64M
        reservations:
          cpus: 0.05
          memory: 16M
    environment:
      - PROMETHEUS_URL=http://vmauth:8427
    hostname: kromgo
    image: ghcr.io/kashalls/kromgo@sha256:965ecc92d68dc1a4a969397855367bbc70da03227a941ea607b73bb7e0b78fd6
    labels:
      - traefik.enable=true
      - traefik.http.routers.kromgo.rule=Host(`stat.techn.is`)
      - traefik.http.routers.kromgo.service=kromgo
      - traefik.http.services.kromgo.loadbalancer.server.port=8080
    read_only: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: 1000:1000
    volumes:
      - ${STACK_DATA_ROOT:?STACK_DATA_ROOT is required}/kromgo/kromgo.yaml:/kromgo/config.yaml:ro
