unauthorized_user:
  url_map:
    - src_paths:
        - /api/v1/write
      url_prefix: http://victoriametrics:8428
    - src_paths:
        - /api/v1/query
        - /api/v1/query_range
        - /api/v1/series
        - /api/v1/labels
        - /api/v1/label/.+/values
        - /api/v1/metadata
      url_prefix: http://victoriametrics:8428
    - src_paths:
        - /insert/loki/api/v1/push
        - /select/.*
      url_prefix: http://victorialogs:9428
    - src_paths:
        - /otlp/.*
      drop_src_path_prefix_parts: 1
      url_prefix: http://tempo:4318
