include:
  - path: ../../services/atuin/compose.yaml
    env_file: &env
      - ../../.env
      - .env
  - path:
      - ../../services/authelia/compose.yaml
      - services/authelia/compose.yaml
    env_file: *env
  - path: ../../services/beszel-agent/compose.yaml
    env_file: *env
  - path:
      - ../../services/cadvisor/compose.yaml
      - services/cadvisor/compose.yaml
    env_file: *env
  - path: services/cloudflared/compose.yaml
    env_file: *env
  - path: ../../services/crowdsec/compose.yaml
    env_file: *env
  - path: ../../services/docker-metrics-proxy/compose.yaml
    env_file: *env
  - path:
      - ../../services/docker-socket-proxy/compose.yaml
      - services/docker-socket-proxy/compose.yaml
    env_file: *env
  - path:
      - ../../services/docker-socket-proxy-api/compose.yaml
      - services/docker-socket-proxy-api/compose.yaml
    env_file: *env
  - path:
      - ../../services/gatus/compose.yaml
      - services/gatus/compose.yaml
    env_file: *env
  - path: services/gatus-ms/compose.yaml
    env_file: *env
  - path: services/gatus-s/compose.yaml
    env_file: *env
  - path: ../../services/searxng/compose.yaml
    env_file: *env
  - path: ../../services/loki/compose.yaml
    env_file: *env
  - path: ../../services/pangolin/compose.yaml
    env_file: *env
  - path:
      - ../../services/newt/compose.yaml
      - services/newt/compose.yaml
    env_file: *env
  - path:
      - ../../services/node-exporter/compose.yaml
      - services/node-exporter/compose.yaml
    env_file: *env
  - path:
      - ../../services/promtail/compose.yaml
      - services/promtail/compose.yaml
    env_file: *env
  - path: ../../services/external-dns/compose.yaml
    env_file: *env
  - path: ../../services/tailscale/compose.yaml
    env_file: *env
  - path:
      - ../../services/technitium/compose.yaml
      - services/technitium/compose.yaml
    env_file: *env
  - path:
      - ../../services/traefik/compose.yaml
      - services/traefik/compose.yaml
    env_file: *env
  - path:
      - ../../services/valkey/compose.yaml
      - services/valkey/compose.yaml
    env_file: *env
  - path:
      - ../../services/whoami/compose.yaml
      - services/whoami/compose.yaml
    env_file: *env

name: mothership

networks:
  external:
    driver: bridge
    enable_ipv6: true
    name: external
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.52.0.0/16
    name: internal
  secondary-status:
    driver: bridge
    enable_ipv6: true
    name: mothership_secondary_status
