services:
  docker-socket-proxy:
    container_name: docker-socket-proxy
    environment:
      - CONTAINERS=1
      - EVENTS=1
      - INFO=1
      - NETWORKS=1
      - PING=1
      - POST=0
      - VERSION=1
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 10s
      test:
        - CMD-SHELL
        - wget -q --spider http://127.0.0.1:2375/_ping || exit 1
      timeout: 10s
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    labels:
      - traefik.enable=false
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
