apiVersion: 1
datasources:
  - access: proxy
    editable: false
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id
      httpMethod: POST
      manageAlerts: false
    name: VictoriaMetrics
    type: prometheus
    uid: victoriametrics
    url: http://victoriametrics:8428
  - access: proxy
    editable: false
    jsonData:
      maxLines: 1000
      otelPreset:
        detection:
          enabled: true
          severity:
            field: severity_text
            source: manual
            valueCase: string
          traceIdField: trace_id
        enabled: true
        tracesDatasourceUid: tempo
    name: VictoriaLogs
    type: victoriametrics-logs-datasource
    uid: victorialogs
    url: http://victorialogs:9428
  - access: proxy
    editable: false
    jsonData:
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: victoriametrics
      tracesToLogsV2:
        customQuery: true
        datasourceUid: victorialogs
        query: 'trace_id:="${__trace.traceId}"'
    name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
