# -*- mode: ruby -*-
# vi: set ft=ruby :

DOMAIN = "technis.lab"
SUBNET = "192.168.56"
ENGINEER_COUNT = 3
CAPTAIN_COUNT = 3
STEWARD_COUNT = 3

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/impish64"
  config.ssh.insert_key = false
  config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key']  # use static key
  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
  (1..ENGINEER_COUNT).each do |i|
    config.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
    end
    config.vm.define "engineer-#{i}" do |j|
      j.vm.hostname = "engineer-#{i}.#{DOMAIN}"
      j.vm.network "private_network", ip: "#{SUBNET}.#{i+10}"
    end
  end
  (1..CAPTAIN_COUNT).each do |i|
    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
    end
    config.vm.define "captain-#{i}" do |j|
      j.vm.hostname = "captain-#{i}.#{DOMAIN}"
      j.vm.network "private_network", ip: "#{SUBNET}.#{i+20}"
    end
  end
  (1..STEWARD_COUNT).each do |i|
    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
    config.vm.define "steward-#{i}" do |j|
      j.vm.hostname = "steward-#{i}.#{DOMAIN}"
      j.vm.network "private_network", ip: "#{SUBNET}.#{i+30}"
    end
  end
end
